Add ability to specify which quantities to PPM reconstruct
quokka-astro/quokka pull request #244
Opened 2023-03-30 04:16 UTC by AstroKriel

Modified the PPM reconstruct function so that the user can specify which quantities to reconstruct (by providing an index to start reconstructing from, and a number of indices to reconstruct), and where to write these reconstructed quantities in the output left and right reconstructed states.

2023-03-30 04:23 UTC, AstroKriel commented on src/hyperbolic_system.hpp
> +	static void ReconstructStatesPPM(amrex::MultiFab const &q_in, amrex::MultiFab &leftState_in, amrex::MultiFab &rightState_in, const int iReadFrom,
@BenWibking I didn't want to change the previous names given to these arguments 'q_in', 'leftState_in', 'rightState_in', but clang-tidy is recommending we make the names consistent. Are you happy for me to do so?

2023-03-30 05:02 UTC, markkrumholz commented
In addition to the variable name issue (which I will let you and Ben resolve), I stronlgy suggest rewriting this PR so the new variables are added at the end of the existing ones, and are assigned default values -- that is, the index to start at and the number of indices to processa are optional extra variables added at the end, which have default values of 0 and a flag value (say -1) that indicates that all indices should be processed. That way you don't have to alter the call structure of any of the existing calls, which all operate on the all quantities. This will greatly reduce the complexity of the PR, because you will only be changing the function signature and implementation, not any of the places where it is called already in the current code.

2023-03-30 05:22 UTC, AstroKriel commented
/azp run

2023-03-30 10:31 UTC, AstroKriel commented
> In addition to the variable name issue (which I will let you and Ben resolve), I stronlgy suggest rewriting this PR so the new variables are added at the end of the existing ones, and are assigned default values -- that is, the index to start at and the number of indices to process are optional extra variables added at the end, which have default values of 0 and a flag value (say -1) that indicates that all indices should be processed. That way you don't have to alter the call structure of any of the existing calls, which all operate on the all quantities. This will greatly reduce the complexity of the PR, because you will only be changing the function signature and implementation, not any of the places where it is called already in the current code.

Thanks Mark, I have updated the function as we discussed, to rather recieve a flag of -1 to indicate looping over all quantites, instead receive a starting index, in combination with the number of variable sto loop over (which was already implemented), so we can loop over any specified range of variables: [iReadFrom, iReadFrom+nvars]. I have also intruced another input argument iWriteFrom, which specifies which quantity's index we want to start writing from.

2023-03-30 10:37 UTC, AstroKriel commented
I can also propogate these changes to the other reconstruction functions (ConstantStates and PLM) if you both are hapy with them.

2023-03-30 22:40 UTC, AstroKriel commented
/azp run

2023-03-30 23:42 UTC, BenWibking commented
I'll try to look at this in detail tomorrow my time.

2023-03-30 23:54 UTC, markkrumholz reviewed
These changes look fine to me, but I'll hold off on approving the PR until Ben has a chance to look too.

2023-04-01 23:55 UTC, BenWibking commented on src/hyperbolic_system.hpp
> +	static void ReconstructStatesPPM(amrex::MultiFab const &q_in, amrex::MultiFab &leftState_in, amrex::MultiFab &rightState_in, const int iReadFrom,
Yeah, go ahead and change the declarations in the class definition to make them consistent.

2023-04-01 23:57 UTC, BenWibking requested changes
Looks good, but please do change the variable names in the declarations so they are consistent.

I've enabled auto-merge, so that once Mark approves, it will merge into development automatically.

2023-04-02 12:31 UTC, BenWibking approved these changes

2023-04-02 13:16 UTC, merged