Print coordinates of cells where flux correction fails
quokka-astro/quokka pull request #383
Opened 2023-09-14 22:54 UTC by psharda

Closes #381

2023-09-14 23:46 UTC, BenWibking requested changes, later dismissed

2023-09-14 23:46 UTC, BenWibking commented on src/RadhydroSimulation.hpp
> +				amrex::Print() << x_coord << ", " << y_coord << ", " << z_coord << ": ";
Can you put this in a separate function? I think that would be better than duplicating the code.

2023-09-15 12:24 UTC, BenWibking approved these changes

2023-09-15 12:38 UTC, psharda commented
/azp run

2023-09-15 13:11 UTC, psharda commented
/azp run

2023-09-15 14:59 UTC, psharda commented
ugh, avatarGPUs throw `nvcc error   : 'cicc' died due to signal 9 (Kill signal)`

2023-09-15 16:14 UTC, BenWibking commented
Somehow the system ran out of memory when it was trying to compile. Maybe try again?

2023-09-15 16:23 UTC, BenWibking commented
/azp run

2023-09-19 02:04 UTC, BenWibking commented
/azp run

2023-09-19 13:24 UTC, merged