Update README
quokka-astro/quokka pull request #398
Opened 2023-09-24 20:30 UTC by psharda

Updated README because `AMREX_GPUS_PER_NODE` is not required anymore, and is not a valid keyword now.

2023-09-24 20:45 UTC, psharda commented
@BenWibking we don't really need to run any tests on this PR, except for the Build and Deploy Docs one maybe? But this test is skipped by default.

2023-09-24 21:35 UTC, BenWibking requested changes, later dismissed

2023-09-24 21:35 UTC, BenWibking commented on README.md
>  where $N$ is the number of GPUs available per compute node.
We can get rid of this phrase.

2023-09-24 21:35 UTC, BenWibking commented on README.md
>  where $N$ is the number of GPUs available per compute node.
We can also get rid of these sentences: "It is necessary to use `-DAMREX_GPUS_PER_NODE` to specify the number of GPUs per compute node. Without this, performance will be very poor."

2023-09-24 21:41 UTC, psharda commented
Oops, maybe I deleted more than what you said?

2023-09-24 21:43 UTC, BenWibking commented
> Oops, maybe I deleted more than what you said?

The rest of the paragraph about the GPU bindings is still true and important, so we should keep that part. Just the part about manually setting the number of GPUs per node is no longer true.

2023-09-24 21:52 UTC, BenWibking commented on README.md
> -**It is necessary to use `-DAMREX_GPUS_PER_NODE` to specify the number of GPUs per compute node. Without this, performance will be very poor. All GPUs on a node must be visible from each MPI rank on
We should keep this text:
```
All GPUs on a node must be visible from each MPI rank on the node for efficient GPU-aware MPI communication to take place via CUDA IPC.** When using the SLURM job scheduler, this means that `--gpu-bind` should be set to `none`.
```

2023-09-25 14:22 UTC, BenWibking approved these changes

2023-09-25 15:30 UTC, merged