Extend HydroState to include MHD-vars for HLLD solver
quokka-astro/quokka pull request #420
Opened 2023-10-09 01:08 UTC by AstroKriel

I have updated the HLLD solver to make reference to the HydroState struct, rather than the MHDState struct (which I have deleted). I have added the two transverse components of b-field to HydroState, and have also added static_assert's to make sure MHD problems only ever use the HLLD solver.

2023-10-09 03:03 UTC, AstroKriel commented
/azp run

2023-10-09 15:44 UTC, BenWibking commented
Clang-tidy remains unhappy: https://github.com/quokka-astro/quokka/actions/runs/6451745075/job/17512771179?pr=420#step:4:1100

The macOS build is failing due to an unrelated problem with the Python installation.

2023-11-21 22:41 UTC, markkrumholz approved these changes, later dismissed

2023-11-21 22:50 UTC, BenWibking commented
The clang-tidy check did not pass. Please do not merge until this is fixed.

2023-11-21 22:56 UTC, BenWibking commented on src/HydroState.hpp
>  	amrex::GpuArray<double, Nmass> massScalar; // mass scalars
Clang-Tidy is complaining about this.

2023-11-28 18:23 UTC, BenWibking commented on src/HydroState.hpp
>  	amrex::GpuArray<double, Nmass> massScalar; // mass scalars
@AstroKriel Can you add `#include "AMReX_Array.H"`?

2023-11-28 18:24 UTC, BenWibking commented on src/HydroState.hpp
>  	amrex::GpuArray<double, Nmass> massScalar; // mass scalars
Ah, I see you already did this. I'll resolve this comment.

2023-11-28 18:24 UTC, BenWibking commented
/azp run

2023-11-28 18:31 UTC, BenWibking requested changes

2023-11-28 18:31 UTC, BenWibking commented on src/hydro_system.hpp
> +		sL.bz = 0.0;
Can you add a comment here that explains that you've just set the magnetic fields to zero for testing purposes?

2023-11-28 18:31 UTC, BenWibking commented on src/hydro_system.hpp
> +		sR.bz = 0.0;
Same comment as above -- can you add a comment in the source here that explains that you've just set the magnetic fields to zero for testing purposes?

2023-11-28 18:31 UTC, BenWibking commented on src/hydro_system.hpp
> +			F_canonical = quokka::Riemann::HLLD<problem_t, nscalars_, nmscalars_, nvar_>(sL, sR, gamma_, 0.0);
Can you add a note that you've hard-coded `bx` to zero for testing purposes?

2023-11-29 14:41 UTC, BenWibking approved these changes

2023-11-29 15:35 UTC, merged