add tests to sphinx docs
quokka-astro/quokka pull request #483
Opened 2024-01-04 04:21 UTC by chongchonghe

### Description
Add a few pages to the Sphinx docs under the tests section.

### Related issues
N/A

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [ ] I have added a description (see above).
- [ ] I have added a link to any related issues see (see above).
- [ ] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [ ] I have tested this PR on my local computer and all tests pass.
- [ ] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [ ] I have requested a reviewer for this PR.

2024-01-04 14:54 UTC, BenWibking requested changes

2024-01-04 14:54 UTC, BenWibking commented on docs/tests/radhydro_pulse.rst
> +and dynamic (:math:`\beta \tau \ll 1`) diffusion regimes, with a uniform
static should be `\beta \tau \ll 1` and dynamic should be `\beta \tau \gg 1`.

2024-01-04 14:54 UTC, BenWibking commented on docs/tests/hydro_shuosher.png
You deleted all of the plots, but didn't add new ones. They don't show up in the compiled HTML.

2024-01-04 15:07 UTC, chongchonghe commented on docs/tests/hydro_shuosher.png
I moved them to attach/ subfolder but they are ignored by git. I forced adding them and now they should appear.

2024-01-04 15:40 UTC, BenWibking commented on docs/tests/attach/radhydro_uniform_advecting_temperature-nobeta.png
Since these figures are all horizontal lines, it might help the user to make these plots instead of the fractional error in temperature (or velocity).

2024-01-04 15:40 UTC, BenWibking approved these changes
Minor comment about figures of horizontal lines. You can change those or not.

2024-01-05 04:57 UTC, chongchonghe commented
> Minor comment about figures of horizontal lines. You can change those or not.

Good point. I'll change it in a separate PR since it requires changing the code.

2024-01-05 05:55 UTC, merged