[WIP] prototype AGORA isolated galaxy
quokka-astro/quokka pull request #506
Opened 2024-01-26 00:38 UTC by BenWibking

### Description
Initializes an isolated galaxy simulation with the AGORA initial conditions.

### Related issues
N/A

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [ ] I have added a description (see above).
- [ ] I have added a link to any related issues see (see above).
- [ ] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [ ] I have tested this PR on my local computer and all tests pass.
- [ ] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [ ] I have requested a reviewer for this PR.

2024-07-09 09:32 UTC, psharda commented
/azp run

2025-04-03 01:03 UTC, BenWibking commented
`max_level = 5`:
```
 plotfile: plt00000
 level   0: number of boxes =      8, volume = 100.00%
          maximum zones =       128 x     128 x     128

 level   1: number of boxes =      8, volume =   0.78%
          maximum zones =       256 x     256 x     256

 level   2: number of boxes =      8, volume =   0.10%
          maximum zones =       512 x     512 x     512

 level   3: number of boxes =      8, volume =   0.01%
          maximum zones =      1024 x    1024 x    1024

 level   4: number of boxes =      9, volume =   0.00%
          maximum zones =      2048 x    2048 x    2048

 level   5: number of boxes =      9, volume =   0.00%
          maximum zones =      4096 x    4096 x    4096
```

`max_level = 9`:
 plotfile: plt00000
 level   0: number of boxes =      4, volume = 100.00%
          maximum zones =       128 x     128 x     128

 level   1: number of boxes =      8, volume = 100.00%
          maximum zones =       256 x     256 x     256

 level   2: number of boxes =     64, volume = 100.00%
          maximum zones =       512 x     512 x     512

 level   3: number of boxes =      4, volume =   0.20%
          maximum zones =      1024 x    1024 x    1024

 level   4: number of boxes =      4, volume =   0.05%
          maximum zones =      2048 x    2048 x    2048

 level   5: number of boxes =      6, volume =   0.01%
          maximum zones =      4096 x    4096 x    4096

 level   6: number of boxes =     17, volume =   0.00%
          maximum zones =      8192 x    8192 x    8192

 level   7: number of boxes =     30, volume =   0.00%
          maximum zones =     16384 x   16384 x   16384

 level   8: number of boxes =     45, volume =   0.00%
          maximum zones =     32768 x   32768 x   32768

 level   9: number of boxes =     52, volume =   0.00%
          maximum zones =     65536 x   65536 x   65536
```

2025-04-19 17:29 UTC, BenWibking commented
/azp run

2025-04-19 19:39 UTC, BenWibking commented
Current failure mode for particle re-init:
```
Reading particles from plotfile ./coarse/plt00000...
ParticleContainer spread across MPI nodes - bytes (num particles): [Min: 0 (0), Max: 13600000 (212500), Total: 13600000 (212500)]
ParticleContainer::Redistribute() time: 0.208718417

[Level 0] Number of valid particles: 0
[Level 0] Number of all particles: 0
[Level 1] Number of valid particles: 0
[Level 1] Number of all particles: 0
[Level 2] Number of valid particles: 0
[Level 2] Number of all particles: 0
[Level 3] Number of valid particles: 0
[Level 3] Number of all particles: 0
[Level 4] Number of valid particles: 0
[Level 4] Number of all particles: 0
```

2025-04-19 19:41 UTC, BenWibking commented on src/problems/AgoraGalaxy/galaxy.cpp
> +			// FIXME(bwibking): when restarting with max_level > max_level_in_file, this reports 0 on all levels:
Restarting with more levels than in the particle file does not work.

2025-05-31 13:44 UTC, BenWibking commented
Current status: restarting with 8x as many MPI ranks leads to a crash
```console
$ mpirun -np 1 ../build/src/problems/AgoraGalaxy/agora_galaxy AgoraGalaxy.in max_timesteps=0
```
Restart:
```console
$ mpirun -np 8 ../build/src/problems/AgoraGalaxy/agora_galaxy AgoraGalaxy_256.in restartfile=chk00000
[many lines skipped]

Restart from checkpoint chk00000
Input grid dimensions on level 0: (256,256,256)
Restart file grid dimensions on level 0: (128,128,128)
Rescaling MultiFabs in restart file by a factor of 2...
Reading chk00000/metadata.yaml...
	quokka_version = 25.03
	git_hash_quokka = 0fb01621667493c049d446134e3e73cd23998b53
	git_hash_amrex = d4b4bf7a4134782eaae78f3140801950709132f8
	units has unknown type! skipping this entry.
	constants has unknown type! skipping this entry.
7::Assertion `!state_new_cc_[lev].contains_nan()' failed, file "/Users/benwibking/amrex_codes/quokka/src/simulation.hpp", line 3218 !!!
SIGABRT
```

2025-05-31 16:39 UTC, BenWibking commented
Ok, the level 1 multifab on restart contains NaN values in valid cells *after* it's interpolated onto the refined grid:
```
Loading Level 1 Multifab...
0::VisMF::Read:  about to read:  ../ncell_128/chk00000/Level_1/Cell
FARead ::  nBoxes = 16  nMessages = 16
FARead ::  hTime = 0.001427267
FARead ::  faCopyTime = 0
FARead ::  mfReadTime = 0.069190587  totalTime = 0.311774931
0::Assertion `!state_new_cc_[lev].contains_nan(0, state_new_cc_[lev].nComp())' failed, file "/ccs/home/wibking/quokka/src/simulation.hpp"
, line 3205 !!!
SIGABRT
```

2025-05-31 16:41 UTC, BenWibking commented
Ah... I think it's failing because the refined new levels are not properly nested with respect to the original levels.

2025-06-02 21:10 UTC, BenWibking commented
/azp run

2025-06-03 00:00 UTC, chongchonghe commented
Looks good to me. Just a minor comment: You have to add the following files to .gitignore to keep the repo clean after `cmake ../.. -DCMAKE_BUILD_TYPE=Release -DAMReX_SPACEDIM=3 -G Ninja` 

```
# Agora galaxy uncompressed data
/extern/agora_data/vcirc.dat
/extern/agora_data/AgoraGalaxy_particles_LOW.txt
```

2025-06-03 00:01 UTC, chongchonghe requested changes
Can you add this to .gitignore?
```
# Agora galaxy uncompressed data
/extern/agora_data/vcirc.dat
/extern/agora_data/AgoraGalaxy_particles_LOW.txt
```

2025-06-03 00:40 UTC, BenWibking commented
> Can you add this to .gitignore?
> 
> ```
> # Agora galaxy uncompressed data
> /extern/agora_data/vcirc.dat
> /extern/agora_data/AgoraGalaxy_particles_LOW.txt
> ```

@chongchonghe Done. See last commit.

2025-06-03 00:49 UTC, chongchonghe approved these changes

2025-06-03 02:49 UTC, merged