Add citation to quokka paper
quokka-astro/quokka pull request #577
Opened 2024-03-20 13:45 UTC by psharda

### Description
Updating the docs to add the citation to the Quokka paper.

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [x] I have added a description (see above).
- [ ] I have added a link to any related issues see (see above).
- [x] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [x] I have tested this PR on my local computer and all tests pass.
- [ ] I have manually triggered the GPU tests with the magic comment `/azp run`.
- [x] I have requested a reviewer for this PR.

2024-03-20 13:46 UTC, psharda commented
Why does this break the docs, lol

2024-03-20 15:28 UTC, BenWibking requested changes

2024-03-20 15:28 UTC, BenWibking commented on docs/citation.rst
> +If you use Quokka or the numerical methods implemented, please cite: Wibking and Krumholz 2023.
Can you add an inline bibtex citation following this:
https://sphinxcontrib-bibtex.readthedocs.io/en/latest/usage.html#role-cite-t

2024-06-07 18:58 UTC, BenWibking approved these changes

2024-06-07 21:25 UTC, merged