Use RSLA in all dust tests
quokka-astro/quokka pull request #811
Opened 2024-12-10 10:02 UTC by chongchonghe

### Description
Since in all practical runs we will use RSLA, it's important to test that our RSLA method gives the exacted result. In this PR, I update RadDust, RadMarshakDust, and RadMarshakDustPE tests to use RSLA. The analytical solutions are updated to include RSLA as well. In all these tests, RSLA changes the results significantly because 1) in the Marshak tests, the problem is in the optically thin limit, so the propagation speed is reduced, or 2) in the RadDust test, the gas has an initial temperature of $T_0$ and cools to a temperature $T_1$ through thermal emission: $T_0$ $C_V T_0 = C_V T_1 + (\hat{c} / c) a_R T_1^4$ . 

This also prepares for the variable RSLA method I'm working on. 

### Related issues
None.

### Checklist
_Before this pull request can be reviewed, all of these tasks should be completed. Denote completed tasks with an `x` inside the square brackets `[ ]` in the Markdown source below:_
- [ ] I have added a description (see above).
- [ ] I have added a link to any related issues (if applicable; see above).
- [ ] I have read the [Contributing Guide](https://github.com/quokka-astro/quokka/blob/development/CONTRIBUTING.md).
- [ ] I have added tests for any new physics that this PR adds to the code.
- [ ] *(For quokka-astro org members)* I have manually triggered the GPU tests with the magic comment `/azp run`.

2024-12-10 10:03 UTC, chongchonghe commented
/azp run

2024-12-10 19:26 UTC, BenWibking requested changes
This seems fine, but I don't think values of $\hat c / c$ of 0.5 or 0.8 are realistic. I don't think we'd ever run with a value greater than $0.1$. Otherwise, we might as well just use the full speed of light, or give up and use a fully implicit method.

2024-12-10 19:26 UTC, BenWibking commented on src/problems/RadDustMG/test_rad_dust_MG.cpp
> +	static constexpr double c_hat_over_c = 0.8;
This is large value for $\hat c/c$. Would it make sense to use $0.1$ instead?

2024-12-10 19:26 UTC, BenWibking commented on src/problems/RadMarshakDust/test_radiation_marshak_dust.cpp
> +constexpr double c_hat_over_c_ = 0.5;
This value also seems unrealistically large.

2024-12-10 19:26 UTC, BenWibking commented on src/problems/RadMarshakDustPE/test_radiation_marshak_dust_and_PE.cpp
> +constexpr double c_hat_over_c_ = 0.5;
Also very large.

2024-12-11 00:50 UTC, chongchonghe commented
> This seems fine, but I don't think values of c ^ / c of 0.5 or 0.8 are realistic. I don't think we'd ever run with a value greater than 0.1 . Otherwise, we might as well just use the full speed of light, or give up and use a fully implicit method.

OK. I set `chat = 0.1 c` in all these tests. Previously I was just testing if the RSLA method is producing results that agree with the analytical ones.

2024-12-11 00:50 UTC, chongchonghe commented
/azp run

2024-12-11 00:54 UTC, BenWibking approved these changes
Ok, looks good to me assuming GPU tests pass.

In general, I think it's better to make the test problems as close to our production simulations as we can, unless it's not possible or there's another good reason not to.

2024-12-11 05:07 UTC, merged